import { GoogleGenAI, Modality } from "@google/genai";
import { ImageFile } from '../types';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

export const generateCharacterProductImage = async (
  characterImage: ImageFile,
  productImage: ImageFile
): Promise<string> => {
  try {
    const textPart = {
      text: "Using the character from the first image and the product from the second image, create a new image. In this new image, the character should be interacting with or using the product. It's very important that the character's art style is preserved. The final image should have the same aspect ratio and dimensions as the first image (the character image).",
    };

    const characterImagePart = {
      inlineData: {
        data: characterImage.base64,
        mimeType: characterImage.mimeType,
      },
    };

    const productImagePart = {
      inlineData: {
        data: productImage.base64,
        mimeType: productImage.mimeType,
      },
    };

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [characterImagePart, productImagePart, textPart],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
      }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error generating image:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate image: ${error.message}`);
    }
    throw new Error("An unknown error occurred during image generation.");
  }
};
